tunnel: 26b4d1b7-28f0-46f1-894a-8165d521bc7f
credentials-file: ~/.cloudflared/26b4d1b7-28f0-46f1-894a-8165d521bc7f.json
origin-ca-pool: ~/.cloudflared/cacert.pem

ingress:
  # Backend API for coffee machine
  - hostname: coffee-api.hydromods.org
    service: http://localhost:3000
    originRequest:
      httpHostHeader: localhost:3000
  
  # Frontend kiosk interface
  - hostname: coffee.hydromods.org
    service: http://localhost:3001
    originRequest:
      httpHostHeader: localhost:3001
  
  # Alternative: k2 subdomain
  - hostname: k2.hydromods.org
    service: http://localhost:3001
    originRequest:
      httpHostHeader: localhost:3001
  
  # Catch-all
  - service: http_status:404